# Generated by Django 6.0.1 on 2026-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_salonslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonslot',
            name='is_active',
        ),
        migrations.AddField(
            model_name='salonslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Maximum appointments allowed in this slot'),
        ),
    ]
