# Generated by Django 6.0.1 on 2026-01-23 19:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_alter_salon_owner_alter_salon_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salon',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salon',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='max_capacity_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='slot_duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='salon',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='plan_expiry',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='plan_start',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='price',
        ),
    ]
