# Generated by Django 6.0.1 on 2026-02-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
