# Generated by Django 6.0.1 on 2026-02-19 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='salon_logos/'),
        ),
        migrations.CreateModel(
            name='SalonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='salon_gallery/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='salons.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
