# Generated by Django 6.0.1 on 2026-02-20 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salon_logo_salonmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='slot_duration',
        ),
    ]
