# Generated by Django 6.0.1 on 2026-02-21 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_remove_slot_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('offer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Customers'), ('LOYAL', 'Loyal Customers Only'), ('NEW', 'New Customers Only')], default='ALL', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='salons.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
