# Generated by Django 6.0.1 on 2026-02-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_broadcastoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastoffer',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Percentage'), ('FLAT', 'Flat Amount')], default='PERCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='broadcastoffer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
