# Generated by Django 6.0.1 on 2026-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_appointment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
